version: '3.8'

services:
  maria-db-main:
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: purepoint
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:7.4.1
    container_name: springboot-purepoint-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mariadb-data:
  redis-data:
